version: 0.2
env:
  variables:
    REPOSITORY_NAME: brain-task
    AWS_ACCOUNT_ID: "304534110140"
    AWS_DEFAULT_REGION: "ap-south-1"

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 304534110140.dkr.ecr.ap-south-1.amazonaws.com/brain-task 

  build:
    commands:
      - echo "Building the Docker image..."
      - IMAGE_TAG= latest   
      - docker build -t 304534110140.dkr.ecr.ap-south-1.amazonaws.com/brain-task :latest .
      - docker tag :latest 304534110140.dkr.ecr.ap-south-1.amazonaws.com/brain-task :latest
      - docker tag $brain-task:$latest 304534110140.dkr.ecr.ap-south-1.amazonaws.com/brain-task:latest

  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 304534110140.dkr.ecr.ap-south-1.amazonaws.com/brain-task:latest
      - docker push 304534110140.dkr.ecr.ap-south-1.amazonaws.com/brain-task:latest
      - echo "Preparing Kubernetes manifests..."
      - mkdir -p build_artifact
      - sed "s|IMAGE_PLACEHOLDER|$REPO_URI:$IMAGE_TAG|g" k8s/deployment.yaml.template > build_artifact/deployment.yaml
      - cp k8s/service.yaml build_artifact/service.yaml
      - echo "Build completed on $(date)"

artifacts:
  files:
    - build_artifact/deployment.yaml
    - build_artifact/service.yaml
