apiVersion: apps/v1
kind: Deployment
metadata:
  name: brain-task-deployment
  labels:
    app: brain-task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brain-task
  template:
    metadata:
      labels:
        app: brain-task
    spec:
      containers:
        - name: brain-task
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
