apiVersion: v1
kind: Service
metadata:
  name: brain-task-svc
  namespace: mind 
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: brain-task
  ports:
    - name: http
      port: 80
      targetPort: 3000

